[build]
  command = "echo 'Static site with serverless functions'"
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Explicitly disable the Next.js plugin
[plugins]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    enable = false
